spring.application.name=inventory-service
server.port=8086

# === Database Configuration ===
spring.datasource.url=jdbc:mysql://localhost:3307/inventory_service
spring.datasource.username=root
spring.datasource.password=mysql
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# === JPA/Hibernate ===
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# === Swagger ===
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs


#management.endpoints.web.exposure.include=*
#management.metrics.distribution.percentiles-histogram.http.server.requests=true
#management.observations.key-values.application=inventory-service
#management.tracing.sampling.probability=1.0

# === Logging ===
logging.level.com.techie.microservices.inventory=DEBUG

# === Endpoint de test pour simuler des pannes (UNIQUEMENT EN DEV) ===
test.failure.enabled=true