version: '4'
services:
  mysql:
    image: mysql:8.3.0
    container_name: mysql-inventory
    environment:
      MYSQL_ROOT_PASSWORD: mysql
    ports:
      - "3307:3306"  # différent du 3306 de order-service
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
